USE [master]
GO

/****** Object:  Database [InventoriForHome]    Script Date: 12/03/2024 10:38:10 p. m. ******/
CREATE DATABASE [InventoriForHome]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'InventoriForHome', FILENAME = N'D:\Programas\SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\InventoriForHome.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'InventoriForHome_log', FILENAME = N'D:\Programas\SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\InventoriForHome_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [InventoriForHome].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [InventoriForHome] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [InventoriForHome] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [InventoriForHome] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [InventoriForHome] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [InventoriForHome] SET ARITHABORT OFF 
GO

ALTER DATABASE [InventoriForHome] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [InventoriForHome] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [InventoriForHome] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [InventoriForHome] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [InventoriForHome] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [InventoriForHome] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [InventoriForHome] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [InventoriForHome] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [InventoriForHome] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [InventoriForHome] SET  DISABLE_BROKER 
GO

ALTER DATABASE [InventoriForHome] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [InventoriForHome] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [InventoriForHome] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [InventoriForHome] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [InventoriForHome] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [InventoriForHome] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [InventoriForHome] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [InventoriForHome] SET RECOVERY FULL 
GO

ALTER DATABASE [InventoriForHome] SET  MULTI_USER 
GO

ALTER DATABASE [InventoriForHome] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [InventoriForHome] SET DB_CHAINING OFF 
GO

ALTER DATABASE [InventoriForHome] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [InventoriForHome] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [InventoriForHome] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [InventoriForHome] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [InventoriForHome] SET QUERY_STORE = ON
GO

ALTER DATABASE [InventoriForHome] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [InventoriForHome] SET  READ_WRITE 
GO

