USE [InventoryForHome]
GO

/****** Object:  Table [dbo].[CatTypeStock]    Script Date: 18/03/2024 12:18:02 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CatTypeStock](
	[IdTypeStock] [int] IDENTITY(1,1) NOT NULL,
	[TypeStockName] [nvarchar](max) NOT NULL,
	[Active] [bit] NOT NULL,
 CONSTRAINT [PK_CatTypeStock] PRIMARY KEY CLUSTERED 
(
	[IdTypeStock] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

